pipeline {
    agent any

    tools {
        jdk 'jdk21'
        maven 'mvn'
    }

    stages {
        stage('Build') {
            steps {
                bat "mvn -B -DskipTests clean package"
            }
        }
        stage('Test') {
            steps {
                bat "mvn test"
            }
        }
        stage('Deliver') {
            steps {
                bat "jenkins\\scripts\\deliver.bat"
            }
        }
    }
}
